routes:
  /:
    template: home
    data: page.home
  /artigos/:
    template: artigos-redirect
    data: false

collections:
  /posts/:
    permalink: /posts/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
